config/routes.rb
Lws::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :documents, only: [:index, :show]
    end
  end

  root to: "high_voltage/pages#show", id: "home"
  resource :subscription, only: [:create]
  resource :feedback, only: [:show, :create]
  resources :writings, only: [:index, :show]
  namespace :writeroom do
    match "/", to: "dashboard#show", as: "writeroom", via: :get
    resources :documents
  end

  resource :spotlight

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :writer

  after_create :notify_requester

  def word_count
    body.blank? ? 0 : body.split.size
  end

  def notify_requester
    DocumentNotifier.writing_started_on(self).deliver unless self.requester.blank?
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :writer
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates_presence_of :email
  validates_format_of :email, with: /.+@.+\..+/i
  validates_presence_of :body

  after_create :send_feedback

  def send_feedback
    Lws::Application.config.notify_list.each do |address|
      Notifier.feedback(address, self).deliver
    end
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

end

app/models/writer.rb
class Writer < ActiveRecord::Base
  has_many :documents, -> { order "created_at" }
  has_one :event

  def first_name
    name.split(" ").first
  end

  def has_selection?
    self.selection.present?
  end


end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < ApplicationController
  respond_to :json

  def index
    respond_with Document.where(archived: false)
  end

  def show
    respond_with Document.find(params[:id])
  end

  private

  def document_params
    params.require(:document).permit(:title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "live_reader"
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def show
    @feedback = Feedback.new(subject: "New Request")
  end
  def create
    @feedback = Feedback.new(feedback_params)
    respond_to do |format|
      if @feedback.save
        format.html { redirect_to root_url, notice: "Thank you, your feedback has been recorded." }
      else
        format.html { redirect_to :back, warning: "Something went wrong." }
      end
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:subject, :email, :body)
  end
end

app/controllers/spotlights_controller.rb
class SpotlightsController < ApplicationController
  layout "spotlight"
  def show
    @document = Document.order("updated_at DESC").first
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save
      flash[:notice] = "Thank you! We'll be in touch soon."
    else
      flash[:warning] = "Ouch, we couldn't save your email. Please try again later"
    end
    redirect_to :back
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email)
  end
end

app/controllers/writeroom/dashboard_controller.rb
class Writeroom::DashboardController < WriteroomController

  def show

  end
end

app/controllers/writeroom/documents_controller.rb
class Writeroom::DocumentsController < WriteroomController

  respond_to :html
  respond_to :json, only: [:update]

  def index
    @documents = Document.where(archived: false)

    respond_with @documents
  end

  def show
    redirect_to action: "edit"
  end

  def new
    @document = Document.new

    respond_with @document
  end

  def edit
    @document = Document.find(params[:id])

    respond_with @document
  end

  def create
    @document = Document.new(document_params)
    flash[:notice] = "The new document was successfully created" if @document.save

    redirect_to edit_writeroom_document_path(@document)
  end

  def update
    @document = Document.find(params[:id])

    if @document.update(document_params)
      Pusher.trigger(pusher_channel, 'patch', 
                     { id:         @document.id.to_s })
    end
    respond_with @document
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to action: "index" }
      format.json { head :no_content }
    end
  end

  private

  def document_params
    params
      .require(:document)
      .permit(:title, :body, :requester)
  end

  def pusher_channel
    "#{Rails.env}_main_channel"
  end
  
end

app/controllers/writeroom_controller.rb
class WriteroomController < ApplicationController
  layout "write_room"
  http_basic_authenticate_with name: ENV['WRITEROOM_USERNAME'], password: ENV['WRITEROOM_PASSWORD']
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  def index
    @writers = Writer.order('created_at').includes(:documents).all
  end

  def show
    @document =  Document.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title_or_default(title)
    return title unless title.blank?
    "<em>Untitled</em>"
  end

  def active_on(title)
    "active" if content_for(:page_title) == title
  end

  def writer_event_title(writer)
    writer.name + (writer.event ? ", #{writer.event.name}" : "")
  end

  def gallery_images
    {
      1 => "Sarah concentrating in Woolfson and Tay",
      2 => "Sarah's words projected on the blinds",
      3 => "Sarah resists the cake and focuses on writing",
      4 => "Contributors make requests at the NPG",
      5 => "A happy patron takes a photo of her piece on the gallery wall",
      6 => "What would you like me to write?",
      7 => "It's a work of art",
      8 => "David thinks",
      9 => "No shortgae of ideas to work with",
      10 => "Sarah at work in the bookshop",
      11 => "Actor Eddie Redmayne watches his contribution being incorporated",
      12 => "Eddie Redmayne's contribution",
      13 => "A small request",
      14 => "Sarah entertians the crowd",
      15 => "Sarah, still smiling",
      16 => "Gemma begins her writing odyssey",
      17 => "Joe at the Jewish Museum's football exhibition",
      18 => "Gemma's mobile live writing setup",
      19 => "David with an audience at the NPG",
      20 => "David with the ultimate literary patron",
      21 => "Joe hears someone else's story",
      22 => "Joe talks to a contributor",
      23 => "A boxing poem, written live",
      24 => "Joe takes sport as his inspiration",
      25 => "Poet Nik Way adds his contribution",
      26 => "Dizz writes live",
      27 => "Sara at the Deptford Lounge",
      28 => "Spread the Word's Paul Sherreard tinkles the keyboard",
      29 => "Deanna deep in thought",
      30 => "Library user Patrick Chike shares a story",
      31 => "Multiple platforms in use",
      32 => "Poetry for inspiration at the Deptford Lounge",
      33 => "Jacon takes to the keyboard",
      34 => "You just stare at the screen until drops of blood form on your forehead",
      35 => "Presenting Molly Naylor",
      36 => "Molly in full flow",
      37 => "Having a laugh at the Roundhouse",
      38 => "Writer needed",
      39 => "Daljit warms up",
      40 => "A spot of planning",
      41 => "Crowd commissions",
      42 => "Not a proposal, but a request is almost as good",
      43 => "Showing off the requests",
      44 => "The best from the Live Writing Series"
    }
  end
end

app/views/application/_flashes.html.haml
#flash
  - flash.each do |key, value|
    %div.alert{ id: "flash_#{ key }", class: (key.to_s == "notice" ? "alert-info" : "") }
      %button.close{ type: "button", :"data-dismiss" => "alert" } &times;
      = value

app/views/application/_javascript.html.haml
= javascript_include_tag app

= yield :javascript

- if Rails.env.test?
  = javascript_tag do
    $.ajaxSetup({ async: false });

- if app=="live_reader" && (Rails.env.staging? || Rails.env.production?)
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-45115483-1']);
    _gaq.push(['_setDomainName', 'livewritingseries.com']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/application/_main.html.haml
!!!
%html
  %head
    %title
      = page_title
    %meta{ charset: "utf-8" }
    %meta{ name: "ROBOTS", content: "NOODP" }
    %meta{ content: (content_for?(:page_description) ? yield(:page_description) : "Live Writing Series"), name: "description"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    = stylesheet_link_tag app, media: "all"
    = csrf_meta_tags
  %body{ class: body_class }
    %header.navbar.navbar-fixed-top{ class: (app == "live_reader" ? "navbar-inverse" : "navbar-default")}
      %nav.navbar-inner
        .container
          = render partial: 'navigation', locals: { app: app }
    .container
      #main{:role => "main"}
        .row
          = render 'flashes'
        .row-fluid
          - if content_for?(:sidebar)
            .sidebar.span3
              = yield :sidebar
          .main{ class: (content_for?(:sidebar) ? "span9" : "span12") }
            = yield
          %footer
    = render partial: 'javascript', locals: { app: app }

app/views/application/_navigation.haml
= link_to "", root_path, :class => 'brand hidden-desktop'
%ul.nav
  %li= link_to 'Home', "/"
  - if app == "live_reader"
    %li{ class: active_on('About')}= link_to 'About', page_path('about')
    %li{ class: active_on('Events')}= link_to 'Events', page_path('events')
    %li{ class: active_on('Writers')}= link_to 'Writers', page_path('writers')
    %li{ class: active_on('Writings')}= link_to 'Writing', writings_path
    %li{ class: active_on('Gallery')}= link_to 'Gallery', page_path('gallery')
    %li{ class: active_on('Contact')}= link_to 'Contact', page_path('contact')
  - else
    %li= link_to 'Stories', writeroom_documents_path
    %li= link_to 'New Story', new_writeroom_document_path

app/views/document_notifier/writing_started_on.text.erb
Hi,

This is an automated message to let you know that Daljit has started writing the piece you requested for the Live Writing Series.

He started writing on <%= @document.created_at.to_formatted_s(:long) %> and the working title is “<%= @document.title %>”.

You can watch him writing live by going to http://livewritingseries.com, where you will also find the other pieces that Daljit has created so far.

Thanks you for partcipating to the Live Writing Series,

  The livewritingseries.com team

app/views/feedbacks/_form.html.haml
= form_for @feedback, url: feedback_url do |f|
  %div{ class: "control-group #{@feedback.errors.include?(:email) ? "error" : ""}"}
    = f.label "email", "Email", class: "control-label"
    .controls
      = f.text_field "email", class: "span6"
      - if @feedback.errors.include?(:email)
        %span.help-inline Please enter your email address
  .control-group
    = f.label "subject", "Subject", class: "control-label"
    .controls
      - if @feedback.subject.blank?
        = f.text_field "subject", class: "span6"
      - else
        = f.hidden_field "subject"
        %span.span6.uneditable-input= @feedback.subject
  %div{ class: "control-group #{@feedback.errors.include?(:body) ? "error" : ""}"}
    = f.label "body", "Message", class: "control-label"
    .controls
      = f.text_area "body", rows: "7", class: "span6"
      - if @feedback.errors.include?(:body)
        %span.help-inline Please enter your feedback here
  .control-group
    .controls
      %button.btn{ type: "submit"} Post

app/views/feedbacks/show.html.haml
= render partial: "form"

app/views/notifier/feedback.text.erb
Hi,
<%= @message.email %> just left the following feedback from the Live Writing Series website:

<%= @message.body %>

app/views/pages/interviews/daljit_nagra.html.haml
- content_for :page_title, "Interviews : Daljit Nagra"
- content_for :extra_body_classes, "interview"
- content_for :sidebar do
  .well
    = image_tag 'logo_on_grey.jpg'
    = render partial: "partials/subscribe"

.row-fluid
  %h3{style: "margin-top: 18px" } An Interview with Daljit Nagra

  %ol.interview
    %li.question
      What were your expectations of live writing?
      .answer
        %p
          I assumed I’d have to spontaneously produce poetry. As I haven’t written new material in a workshop session, or to demand in a few minutes, for over a decade I was terrified I may have lost the knack. The session lived up to my expectation of having to produce poems in quick succession and I was pleased by the many helpful suggestions from the public that encouraged my creativity.

    %li.question
      How different was it from a normal writing day for you?
      .answer
        %p
          I never write to order and if I’m commissioned to write a poem I spend several months working on a text. So this sitting in a public space and being the focus of expectation was highly unusual for me. I normally write in snatches – a half here or there. I rarely spend more than an hour just working on my poetry. In some ways, the four hour session helped to connect me back to working in a grand concentrated manner. I need to find four hour slots in which to do write!

    %li.question
      What was the best moment?
      .answer
        %p
          The best moment happened about five times. Each time I felt I the emergence of a poem I felt relieved and excited. Relieved that my creativity was functioning, excited that the written piece might be good enough for my next poetry collection. I think one of the pieces might work for my next collection; I’ll show it to my editor at some point. The really amazing moment was meeting people who had no relationship to poetry whatsoever and who found themselves making suggestions for a poem and then finding I’d written them a poem. I hope they’ll feel poetry is a normal living activity not only involving bald men a few hundred years ago.

    %li.question
      Your poetry readings are always wonderfully animated. How does writing live, on screen and on webcam, compare with that kind of performance? 
      .answer
        %p
          This was a performance, for sure. Several members of the public suggested ideas for a poem and I told them to come back in a bit and see if I’ve written a poem. Three members of the public returned to find I’d written a poem based on their thoughts. Instead of feeling in control in one of my usual readings where the audience sits quietly I was mindful the audience was a participant and I had to respect their vision. I don’t know if the people who inspired my poems liked the pieces but they seemed happy that I had included their names in the poem.

    %li.question
      Finish this sentence. If live writing were an animal, it would be...
      .answer
        %p
          \...a chameleon because I’d have to constantly adapt to the knowledge requirements of the poems and the different styles required of me.  


.row-flow
  = image_tag "writers/daljit_nagra.jpg", class: "img", style: "margin: 25px;"

app/views/pages/interviews/david_varela.html.haml
- content_for :page_title, "Interviews : David Varela"
- content_for :extra_body_classes, "interview"
- content_for :sidebar do
  .well
    = image_tag 'logo_on_grey.jpg'
    = render partial: "partials/subscribe"

.row-fluid
  %h3{style: "margin-top: 18px" } An Interview with David Varela

  %ol.interview
    %li.question
      You were writing stories in the presence of Her Majesty Elizabeth I. Will you look back on that as the best moment in your life?

      .answer
        %p
          It was definitely one of the most intimidating. There’s an edge of fear to writing for a live audience, and even more so when it’s the hallowed halls of a national gallery. Everything I was doing was suddenly Art. 
        %p
          Well, I suppose we’re being supported by the Arts Council so we’re already artists. I’m just not used to the capital A.


    %li.question
      What was the highlight of the evening?

      .answer
        Towards the end of the night, when the crowd was starting to thin out, I was able to see the person who’d commissioned the piece I was writing as she looked up at the screen where it was projected, and she was laughing along and putting her hand over her mouth and finally taking photos of her piece of work up there, on the wall of the gallery. And because it was the last piece of the night, she came over and said thank you and we had a funny, sweet chat about what I’d written. It was the best kind of audience interaction. 


    %li.question
      Most odd request?

      .answer
        “On the Nobility of Otters.” Although the girls who asked for a Greek tragedy about Anne Boleyn were pushing the boundaries of the expected too.


    %li.question
      Is live writing better than sitting at home alone at your desk?

      .answer
        %p
          It’s certainly more productive. In four hours, I wrote 22 different pieces and 3,500 words, while still finding time to stop and talk and sort through all the requests coming in on paper and online. I had far more requests than I could handle, and around 4,000 people milling about in that hall. There was so much to assimilate and so much to write. It was like whitewater rafting on the stream of consciousness. 

        %p
          So I’d recommend it for short periods, but if you want to write every day, your desk at home is still the safest place for it. 


    %li.question
      Any top tips for the writers up next? What are the most important attributes for excellent live writing?
      .answer
        Be open to ideas, focus hard when you can, and be prepared for some heckling. 

.row-flow
  = image_tag "events/npg_david.jpg", class: "img span12"

app/views/pages/interviews/gemma_seltzer.html.haml
- content_for :page_title, "Interviews : Gemma Seltzer"
- content_for :extra_body_classes, "interview"
- content_for :sidebar do
  .well
    = image_tag 'logo_on_grey.jpg'
    = render partial: "partials/subscribe"

.row-fluid
  %h3{style: "margin-top: 18px" } An Interview with Gemma Seltzer

  %ol.interview
    %li.question
      You&rsquo;d seen a couple of live writing events before yours. Did they reassure you or make you more nervous?
      .answer
        %p
          Both David Varela&rsquo;s event in front of a constant stream of thousands of people, and Sarah Butler&rsquo;s more intimate session with a quieter crowd necessitated stamina and courage from the writers. I was nervous that I wouldn&rsquo;t last from morning to evening, wouldn&rsquo;t find enough material to inspire, and that I would freeze in front of my online audience. Happily, after my first story was complete, I found a good rhythm and also that I had plenty to say!

    %li.question
      You&rsquo;ve talked to strangers in previous writing projects. How did this experience differ?
      .answer
        %p
          My first digital writing project, 
          %em Speak to Strangers, 
          involved chatting to members of the public over one hundred days and writing very short stories directly from the experience. For the 
          %em Live Writing Series, 
          which also included random interactions with people,  the strangers were just one part of the experience. I also used the sights and sounds of the places I visited, the notes and comments from audiences online, and the rhythms of walking and moving through the city as the basis for my writing. 

    %li.question
      You covered a lot of ground on your trek across London. What was your favourite writing spot?
      .answer
        %p
          I loved the sense of the city changing from place to place, each location offering a new perspective for me. I enjoyed the quirky pub I found in Holland Park. The music was too loud, the lights too low, and the clientele too boisterous. At 5pm, people were finishing work and relaxing. It was a place that was in no way conducive to creating stories live, but I enjoyed the challenge of writing at odds to my surroundings.

    %li.question
      Did you feel like you were writing in public or writing in secret?
      .answer
        %p
          Both, at different times. I did have some signs that I propped up showing the project logo, and a note that said. &ldquo;I&rsquo;m writing a story. Tell me what should happen next.&rdquo; In other moments, I let the people around me know what I was doing, showed them the website and invited them to respond. Without a big screen nearby, I was able to write more freely perhaps, than some of the other writers will.

    %li.question
      Favourite moment?
      .answer
        %p
          Someone tweeted &lsquo;Harriet Bardot&rsquo; as a character&rsquo;s name, which evoked an elegant, haphazard sort of person in my mind. She ended up in all of the stories, stumbling through her life. And also, in the Wellcome Collection, I shared a table with two scientists. Towards the end, one even dashed to the bookshop and selected titles I could incorporate into the piece. Our conversation offered colour and much liveliness to my stories.

    %li.question
      Is there anything you&rsquo;d do differently next time?
      .answer
        %p
          Maybe for longer! I found it productive and inspiring. I must be a secret exhibitionist, because I quite liked the webcam recording. It would be interesting to have at least one of the locations with a big screen linked up, so I could dip into writing live for an hour in both public and online, before swiftly typing the final full stop and packing up to head to the next place.
.row-flow
  = image_tag "events/ldn_gemma.jpg", class: "img span12"

app/views/pages/interviews/jacob_sam-la_rose.html.haml
- content_for :page_title, "Interviews : Jacob Sam-La Rose and the Podium Poets "
- content_for :extra_body_classes, "interview"
- content_for :sidebar do
  .well
    = image_tag "logo_on_grey.jpg"
    = render partial: "partials/subscribe"

.row-fluid
  %h3{style: "margin-top: 18px" } An Interview with Jacob Sam-La Rose, Deanna Rodger and Dizz Tate

  %ol.interview
    %li.question
      How did the live writing process differ from your normal practice?
      .answer
        %p
          JSLR: Not a great deal, not the way we actually managed the live-writing
          workshop. It became about writing freely, which is part of my process anyway.
          I do appreciate the potential, for the live-writing process, however, if framed in a 
          different way. For example, we had he screen set up in our room that initially would 
          have captured the 'live' aspect of what was being done, and would have placed some 
          interesting psychological challenges on the writer (heightened awareness of an audience, etc.).
        %p
          DR: It was muchmore instant. Plus writing on a computer means that you can't scribble
          around your writing. I was keen that people would be able to read it how I needed them
          to read it, as I was aware that I wouldn't get a chance to say it.
        %p
          DT: It didn't really differ; I wrote in the same way.
          I guess the difference is that I didn't go back and edit, but there 
          was something really freeing about just getting the words on the page
          and not over thinking it too much. 
        %p
          JSLR: It would have been interesting to see if there was anything that could be
          done with pen and paper responses from other people in the room based on what
          they were seeing on-screen...
    %li.question
      Did you have a sense that there was an audience?
      .answer
        %p
          JSLR: No! When I locked into the writing, it was a relationship between me, my
          thoughts, and the screen. I carried on regardless.
        %p
          DT: A little bit which was quite strange! My mum was texting me to say
          she was watching it, so I had the sense of her there. 
        %p
          DR: Yes and no. I tried to forget that it was live as that was a distraction.
    %li.question
      Did you enjoy it?
      .answer
        %p
          DT: Yes! It was really cool to feel like a part of a community in a way.
          Writing can be quite a lonely process so to have that interaction and
          to open up a dialogue was really exciting.
        %p
          DR: Very much so.
        %p
          JSLR: Yes!
    %li.question
      Do you think it’s harder to write poetry live than prose?
      .answer
        %p
          JSLR: To an extent, possibly, but it's a matter of how the challenge is managed.
          I can imagine that an awareness of an audience might be off-putting to some,
          but with that fear put aside, and with the sense that live writing captures the 
          writing process warts and all, it's not such a problem. I think, with the way that
          we engaged with the process, there wasn't a specific challenge to produce a 
          finished piece within a finite period of time. I can imagine it being different for
          a poest who's managing the perceived expectations of an audience that's specifically
          gathered to see what they produce by the end of the allotted session...
          %br/
          %br/
          Also, to be fair, I didn't write poetry in my slot, so my experience may have been 
          different from my participants'...
        %p
          DR: I have never written prose live before and am quite comfortable writing poetry live.
        %p
          DT: I think it would be the same. I suppose with poetry you think about
          the rhythm and sound maybe slightly more, but once you get into a poem,
          I think that comes naturally in the same way you get into writing a story.
    %li.question
      Are you a fan of technology? Do you think it helps or hinders the writing process?
      .answer
        %p
          DR: I am a fan. I think it does both. Sometimes I find it easier to use a notebook
          and pen, other times easier and quicker to use a device.
        %p
          JSLR: Yes. As with all tools, I think technology can help, depending on how it's 
          used or engaged with.
        %p
          DT: I love that technology opens things up; it's so easy to create a
          conversation now with almost anyone.
          I like the idea of using an audience in the writing process;
          it adds voices and dialogue and changes things up. Writing is a way 
          of describing a world on paper, and it makes sense to include our
          surroundings and other voices, in order to understand that world better.

app/views/partials/_subscribe.html.haml
.subscribe{ style: "margin-top: 25px" }
  = form_for Subscription.new, url: subscription_path do |f|
    .row-fluid{style: "text-align: center"}
      = f.label :email, "Keep me informed:"
      .input-append
        = f.text_field :email, placeholder: "me@example.org", class: "span9"
        = f.button "Go!", class: "btn"

app/views/partials/_writers_sidebar.html.haml
.well

  = image_tag "logo_on_grey.jpg"

  %ul.nav.nav-list
    %li.nav-header.hidden
      Interviews
    %li
      %a(href="#first")
        %i.icon.icon-user
        Sarah Butler
    %li
      %a(href="#second")
        %i.icon.icon-user
        Joe Dunthorne
    %li
      %a(href="#third")
        %i.icon.icon-user
        Daljit Nagra
    %li
      %a(href="#fourth")
        %i.icon.icon-user
        Molly Naylor
    %li
      %a(href="#fifth")
        %i.icon.icon-user
        Jacob Sam-La Rose
    %li
      %a(href="#sixth")
        %i.icon.icon-user
        Gemma Seltzer
    %li
      %a(href="#seventh")
        %i.icon.icon-user
        David Varela

app/views/spotlights/show.html.haml
.container
  %h1
    = @document.try(:title).try(:html_safe)
  .text
    = @document.try(:body).try(:html_safe)

app/views/writeroom/dashboard/show.html.haml
%h3 Welcome dear writer

%p
  Probably you want to be on the
  = link_to "story index", writeroom_documents_path

app/views/writeroom/documents/_form.haml
= form_for @document, url: (@document.new_record? ? writeroom_documents_path : writeroom_document_path(@document)), html: { class: "form-horizontal" } do |f|
  - if @document.errors.any?
    #error_explanation
      %h2= "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:"
      %ul
        - @document.errors.full_messages.each do |msg|
          %li= msg

  .row
    .span9
      = f.text_field :title, class: "span12",  placeholder: "Untitled - story title goes here"
    .span3
      - unless @document.new_record?
        #connection-status.label
          Initialising...
        #word_count.badge
          = pluralize @document.word_count, 'word', 'words'
  .row{ style: "margin-top: 20px" }
    .span12
      - if @document.new_record?
        .span9
          .input-prepend.span9
            %span.add-on
              %i.icon-envelope
            = f.text_field :requester, class: "span12", placeholder: "requester email address"
          .span3.text-right
            = f.submit class: "btn"
      - else
        = f.text_area :body, id: 'redactor'

- content_for :navigation do
  %li
    = link_to new_writeroom_document_path do
      %i.icon-file
      New Document

app/views/writeroom/documents/edit.html.haml
= render 'form'

- content_for :javascript do
  :javascript
    WriteRoom.require('documents/edit', #{@document.id});

app/views/writeroom/documents/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Title
      %th Words
      %th Last Updated
      %th

  %tbody
    - @documents.each do |document|
      %tr
        %td
          = link_to edit_writeroom_document_path(document) do
            %i.icon-pencil
            = raw title_or_default(document.title)
        %td= document.word_count
        %td= time_tag document.updated_at, format: :short
        %td
          = link_to writeroom_document_path(document), method: :delete, data: { confirm: 'Are you sure?' } do
            %i.icon-trash

- content_for :navigation do
  %li
    = link_to new_writeroom_document_path do
      %i.icon-file
      New Document

app/views/writeroom/documents/new.html.haml
= render 'form'

app/views/writings/index.html.haml
- content_for :page_title, "Writings"
- content_for :extra_body_classes, "writings"
- content_for :sidebar do
  .well
    = image_tag "logo_on_grey.jpg"
    = render partial: "partials/subscribe"

- @writers.each do |writer|
  - if writer.documents.any?
    %h3= writer_event_title(writer)

    %ul
      - if writer.has_selection?
        %li
          = link_to "#{writer.first_name.upcase}'s SELECTED HIGHLIGHT", page_path("selections/#{writer.selection}")
      - writer.documents.each do |document|
        %li
          = link_to document.title, writing_path(document)

app/views/writings/show.html.haml
- content_for :page_title, "Writings"
- content_for :extra_body_classes, "writing"
- content_for :sidebar do
  .well
    = image_tag "logo_on_grey.jpg"
    = render partial: "partials/subscribe"

%h3{ style: "margin-top: 18px" }= @document.try(:title).try(:html_safe)

%p
  = @document.try(:body).try(:html_safe)